/**
 * Coupling-F — the OpenAPI codegen contract guard.
 *
 * This does NOT re-run the generator (that needs the backend python/venv, which
 * is not available in a FE-only test lane). Instead it asserts the *committed*
 * artifacts are present + well-formed + mutually consistent, so a stray
 * hand-edit or a botched `npm run gen:types` cannot land silently:
 *
 *   1. `webui/openapi.json` exists, parses, and looks like an OpenAPI doc.
 *   2. `src/lib/api-types.gen.ts` exists, carries the generated banner, and
 *      exports the four openapi-typescript shapes (paths/webhooks/components/operations).
 *   3. Every enum + request/shared model schema in openapi.json surfaces in the
 *      generated `components["schemas"]` block (the request/enum coverage the
 *      wave promises), and Pydantic-v2 enums render as literal unions.
 *   4. Every src/ module that adopts it does so with a TYPE-ONLY import, so the
 *      generated module stays fully erased at compile time (0 runtime bytes).
 *
 * The live drift gate is `npm run check:types` (regenerate + `git diff --exit-code`);
 * this test is its offline, always-runnable companion.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEBUI_DIR = resolve(HERE, '../../..');
const OPENAPI_JSON = resolve(WEBUI_DIR, 'openapi.json');
const GEN_TS = resolve(WEBUI_DIR, 'src/lib/api-types.gen.ts');

describe('OpenAPI codegen artifacts (Coupling-F)', () => {
  it('commits a well-formed openapi.json', () => {
    expect(existsSync(OPENAPI_JSON)).toBe(true);
    const spec = JSON.parse(readFileSync(OPENAPI_JSON, 'utf8'));
    expect(typeof spec.openapi).toBe('string');
    expect(spec.openapi.startsWith('3.')).toBe(true);
    expect(spec.paths && Object.keys(spec.paths).length).toBeGreaterThan(0);
    expect(spec.components?.schemas).toBeTruthy();
  });

  it('commits a generated api-types.gen.ts with the four openapi-typescript shapes', () => {
    expect(existsSync(GEN_TS)).toBe(true);
    const src = readFileSync(GEN_TS, 'utf8');
    // Generated banner — signals "do not hand-edit".
    expect(src).toMatch(/auto-generated by openapi-typescript/i);
    // Each shape is exported as either an interface (paths/components/operations)
    // or a type alias (empty `webhooks` → `Record<string, never>`).
    for (const shape of ['paths', 'webhooks', 'components', 'operations']) {
      expect(src).toMatch(new RegExp(`export (interface|type) ${shape}\\b`));
    }
  });

  it('surfaces every openapi schema (enums + request/shared models) in the generated components', () => {
    const spec = JSON.parse(readFileSync(OPENAPI_JSON, 'utf8'));
    const gen = readFileSync(GEN_TS, 'utf8');
    const schemas = Object.keys(spec.components?.schemas ?? {});
    expect(schemas.length).toBeGreaterThan(20);
    // openapi-typescript emits each schema name as a key under components.schemas.
    // Guard a representative sample of enums + request bodies rather than every
    // name (some FastAPI-suffixed dupes are expected) — but assert 100% presence.
    const missing = schemas.filter((name) => !gen.includes(`${name}:`));
    expect(missing).toEqual([]);
  });

  it('renders Pydantic-v2 enums as literal unions (not runtime enum objects → 0 runtime bytes)', () => {
    const gen = readFileSync(GEN_TS, 'utf8');
    // Verdict is a known 3-value enum; must be a string-literal union, and there
    // must be NO emitted `enum ` keyword anywhere (that would add runtime bytes).
    expect(gen).toMatch(/Verdict:\s*"[A-Z_]+"\s*\|\s*"[A-Z_]+"/);
    expect(gen).not.toMatch(/\benum\s+[A-Za-z]/);
  });

  it('is imported TYPE-ONLY everywhere (stays fully erased, 0 runtime bytes)', () => {
    // The generated module carries only `interface`/`type` declarations, so a VALUE
    // import (`import { components } from …`) would emit a real runtime require for a
    // module with nothing in it. Adoption is expected and welcome — enum vocabularies
    // pinned to the schema is the whole point — but it must stay `import type`.
    const offenders: string[] = [];
    // Anchored at line start and forbidden from crossing a `;`, so one match is
    // exactly one import statement.
    const anyImport = /^import\s+([^;]*?)from\s*['"][^'"]*api-types\.gen(?:\.ts)?['"]/gm;
    const walk = (dir: string) => {
      for (const ent of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, ent.name);
        if (ent.isDirectory()) {
          if (ent.name === 'node_modules') continue;
          walk(p);
        } else if (
          /\.(ts|tsx)$/.test(ent.name) &&
          !/\.test\.(ts|tsx)$/.test(ent.name) && // tests may reference the name as a string
          p !== GEN_TS
        ) {
          const src = readFileSync(p, 'utf8');
          for (const m of src.matchAll(anyImport)) {
            if (!/^\s*type\b/.test(m[1])) offenders.push(`${p}: ${m[0].slice(0, 80)}`);
          }
        }
      }
    };
    walk(resolve(WEBUI_DIR, 'src'));
    expect(offenders).toEqual([]);
  });

  it('backs the ground-truth outcome picker with the SAME vocabulary the schema declares', () => {
    // G1: the analyst-outcome control must offer exactly the backend enum. The
    // compile-time guard in `grading.tsx` (`FeedbackOutcomeCoverage`) proves coverage
    // against the GENERATED type; this proves the generated type still matches the
    // committed spec, so the two cannot quietly agree on a stale vocabulary.
    const spec = JSON.parse(readFileSync(OPENAPI_JSON, 'utf8'));
    const declared: string[] = spec.components?.schemas?.FeedbackOutcome?.enum ?? [];
    expect(declared.length).toBeGreaterThan(0);
    const gen = readFileSync(GEN_TS, 'utf8');
    const line = gen.split('\n').find((l) => l.trim().startsWith('FeedbackOutcome:'));
    expect(line).toBeTruthy();
    const generated = [...(line as string).matchAll(/"([a-z_]+)"/g)].map((m) => m[1]);
    expect(generated.sort()).toEqual([...declared].sort());
  });

  it('keeps the ground-truth INTENT flag on the case-action wire, defaulted off', () => {
    // G1: `disposition` alone cannot say who chose it — `case_manager.apply()` derives
    // one from the LLM verdict, so a client echoing the stored value back is quoting
    // the model. `disposition_declared` is the separate assertion that a human picked
    // it, and the Console sends it only from the picker's onChange. If the backend ever
    // drops the field, every close silently degrades to "applied but unlabelled" with
    // no type error to catch it — so pin the contract to the committed spec.
    const spec = JSON.parse(readFileSync(OPENAPI_JSON, 'utf8'));
    for (const schema of ['CaseAction', 'BulkCaseAction']) {
      const prop = spec.components?.schemas?.[schema]?.properties?.disposition_declared;
      expect(prop, `${schema}.disposition_declared`).toBeTruthy();
      expect(prop.type).toBe('boolean');
      // Fail-safe by default: an omitted flag must never classify.
      expect(prop.default).toBe(false);
    }
  });
});
